-- Never edit a migration that has been merged: add V2__..., V3__... instead.

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(120) NOT NULL,
    email         VARCHAR(160) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE parcels (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id    BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name        VARCHAR(120) NOT NULL,
    governorate VARCHAR(60)  NOT NULL,
    latitude    DOUBLE PRECISION NOT NULL,
    longitude   DOUBLE PRECISION NOT NULL,
    area_ha     DOUBLE PRECISION,
    tree_count  INTEGER,
    variety     VARCHAR(60),
    irrigated   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_parcels_owner ON parcels (owner_id);

CREATE TABLE predictions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    parcel_id     BIGINT      REFERENCES parcels (id) ON DELETE SET NULL,
    type          VARCHAR(30) NOT NULL,
    request_json  TEXT,
    response_json TEXT        NOT NULL,
    mock          BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_predictions_user_created ON predictions (user_id, created_at);
